sudo: required
language: node_js
notifications:
  email: false
services:
  - docker
node_js:
  - 8
before_install:
  - docker version
  - docker run -d -p 127.0.0.1:5984:5984 klaemo/couchdb:1.6.1
  - docker build -t hoodiehq/hoodie-app-tracker .
  - npm prune
script:
  - npm run now-start &
  - cypress run
after_success:
  - npm run semantic-release
deploy:
- provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push hoodiehq/hoodie-app-tracker
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - /home/travis/.cypress/Cypress
